apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yzt8hvgz6-go 
  janus-idp.io/tekton: yzt8hvgz6-go
  backstage.io/kubernetes-id: yzt8hvgz6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yzt8hvgz6-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml