apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yzt8hvgz6-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yzt8hvgz6-go 
  name: yzt8hvgz6-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yzt8hvgz6-go 
